services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: "YRbrDepYQdiQFJC4mhQN4Q"
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./kafka/server.properties:/opt/kafka/config/kraft/server.properties:ro
    command: >
      bash -lc '
        set -e
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          /opt/kafka/bin/kafka-storage.sh format -t "$KAFKA_CLUSTER_ID" -c /opt/kafka/config/kraft/server.properties
        fi
        /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
      '

volumes:
  kafka-data: